config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "tickets#index"

  resources :tickets do
  	collection do
        post :create_from_json
    end
  end
  resources :excavators
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
	belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_many :excavators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/excavators_controller.rb
class ExcavatorsController < ApplicationController
  before_action :set_excavator, only: [:show, :edit, :update, :destroy]

  # GET /excavators
  # GET /excavators.json
  def index
    @excavators = Excavator.all
  end

  # GET /excavators/1
  # GET /excavators/1.json
  def show
  end

  # GET /excavators/new
  def new
    @excavator = Excavator.new
  end

  # GET /excavators/1/edit
  def edit
  end

  # POST /excavators
  # POST /excavators.json
  def create
    @excavator = Excavator.new(excavator_params)

    respond_to do |format|
      if @excavator.save
        format.html { redirect_to @excavator, notice: 'Excavator was successfully created.' }
        format.json { render :show, status: :created, location: @excavator }
      else
        format.html { render :new }
        format.json { render json: @excavator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excavators/1
  # PATCH/PUT /excavators/1.json
  def update
    respond_to do |format|
      if @excavator.update(excavator_params)
        format.html { redirect_to @excavator, notice: 'Excavator was successfully updated.' }
        format.json { render :show, status: :ok, location: @excavator }
      else
        format.html { render :edit }
        format.json { render json: @excavator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excavators/1
  # DELETE /excavators/1.json
  def destroy
    @excavator.destroy
    respond_to do |format|
      format.html { redirect_to excavators_url, notice: 'Excavator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excavator
      @excavator = Excavator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excavator_params
      params.require(:excavator).permit(:ticket_id, :company_name, :address, :city, :state, :zip, :crew_on_site)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_from_json
  	# Create Ticket
  	@ticket = Ticket.new do |t|
  		t.request_number = params['RequestNumber']
  		t.sequence_number = params['SequenceNumber']
  		t.request_type = params['RequestType']
  		t.response_due_date_time = params['DateTimes']['ResponseDueDateTime']
  		t.primary_service_area_code = params['ServiceArea']['PrimaryServiceAreaCode']['SACode']
  		t.additional_service_area_code = params['ServiceArea']['AdditionalServiceAreaCodes']['SACode']
  		t.well_known_text = params['ExcavationInfo']['DigsiteInfo']['WellKnownText']
  	end

	if @ticket.save
		# Create Excavator
	  	@excavator = Excavator.new do |e|
	  		e.company_name = params['Excavator']['CompanyName']
	  		e.address = params['Excavator']['Address']
	  		e.city = params['Excavator']['City']
	  		e.state = params['Excavator']['State']
	  		e.zip = params['Excavator']['Zip']
	  		e.crew_on_site = params['Excavator']['CrewOnsite']
	  	end
	  	@ticket.excavators << @excavator
	  	
		render json: @ticket, status: :created
	else
		render json: @ticket.errors, status: :unprocessable_entity
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:request_number, :sequence_number, :request_type, 
      	:response_due_date_time, :primary_service_area_code, :additional_service_area_code, :well_known_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excavators_helper.rb
module ExcavatorsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/excavators/_excavator.html.erb
<div class="row">
    <div class="form-group col-sm-12">
      <label>Ticket</label>
      <%= excavator.ticket.id %>
    </div>
    <div class="col-sm-6">
      <span>Company Name:</span>
      <label><%= excavator.company_name %></label>
    </div>
    <div class="form-group col-sm-6">
      <span>Address:</span>
      <label><%= excavator.address %></label>
    </div>
    <div class="form-group col-sm-6">
      <span>City:</span>
      <label><%= excavator.city %></label>
    </div>
    <div class="form-group col-sm-6">
      <span>State:</span>
      <label><%= excavator.state %></label>
    </div>
    <div class="form-group col-sm-6">
      <span>Zip:</span>
      <label><%= excavator.zip %></label>
    </div>
    <div class="form-group col-sm-6">
      <span>Crew on Site:</span>
      <label><%= excavator.crew_on_site %></label>
    </div>
</div>

app/views/excavators/_form.html.erb
<%= form_with(model: excavator, local: true) do |form| %>
  <% if excavator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(excavator.errors.count, "error") %> prohibited this excavator from being saved:</h2>

      <ul>
      <% excavator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-12">
      <label>Ticket</label>
      <%= form.collection_select :ticket_id, Ticket.all, :id, :id, {}, {class: 'form-control'} %>
    </div>
    <div class="form-group col-sm-6">
      <label>Company Name</label>
      <%= form.text_field :company_name, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Address</label>
      <%= form.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>City</label>
      <%= form.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>State</label>
      <%= form.text_field :state, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Zip</label>
      <%= form.text_field :zip, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Crew on Site</label>
      <%= form.text_field :crew_on_site, class: 'form-control' %>
    </div>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/excavators/edit.html.erb
<h1>Editing Excavator</h1>

<%= render 'form', excavator: @excavator %>

<%= link_to 'Show', @excavator %> |
<%= link_to 'Back', excavators_path %>

app/views/excavators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Excavators</h1>

<table class="table">
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Company Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Crew on Site</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @excavators.each do |excavator| %>
      <tr>
        <td><%= link_to excavator.ticket.id, excavator.ticket %></td>
        <td><%= excavator.company_name %></td>
        <td><%= excavator.address %></td>
        <td><%= excavator.city %></td>
        <td><%= excavator.state %></td>
        <td><%= excavator.zip %></td>
        <td><%= excavator.crew_on_site %></td>
        <td>
          <%= link_to 'Show', excavator %>
          <%= link_to 'Edit', edit_excavator_path(excavator) %>
          <%= link_to 'Destroy', excavator, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excavator', new_excavator_path %>

app/views/excavators/new.html.erb
<h1>New Excavator</h1>

<%= render 'form', excavator: @excavator %>

<%= link_to 'Back', excavators_path %>

app/views/excavators/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "excavator", locals: {excavator: @excavator} %>

<%= link_to 'Edit', edit_excavator_path(@excavator) %> |
<%= link_to 'Back', excavators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boss</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyAgmEdjzBhC_YvPeOjcX8TkzNi7Pj4AeCo"></script>
	<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
	<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>	

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Boss</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', '/' %></li>
          <li class="<% concat 'active' if controller_name == 'excavators' %>"><%= link_to 'Excavators', excavators_path %></li>
          <li class="<% concat 'active' if controller_name == 'tickets' %>"><%= link_to 'Tickets', tickets_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
  </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-6">
      <label>Request Number</label>
      <%= form.text_field :request_number, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Sequence Number</label>
      <%= form.text_field :sequence_number, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Request Type</label>
      <%= form.text_field :request_type, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Response Due DateTime</label>
      <%= form.text_field :response_due_date_time, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Primary SACode</label>
      <%= form.text_field :primary_service_area_code, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Additional SACode</label>
      <%= form.text_field :additional_service_area_code, class: 'form-control' %>
    </div>
    <div class="form-group col-sm-6">
      <label>Well Known Text</label>
      <%= form.text_field :well_known_text, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Request Number</th>
      <th>Sequence Number</th>
      <th>Request Type</th>
      <th>Response Due Date Time</th>
      <th>Primary SACode</th>
      <th>Additional SACode</th>
      <th>Well Known Text</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.request_number %></td>
        <td><%= ticket.sequence_number %></td>
        <td><%= ticket.request_type %></td>
        <td><%= ticket.response_due_date_time %></td>
        <td><%= ticket.primary_service_area_code %></td>
        <td><%= ticket.additional_service_area_code %></td>
        <td><%= ticket.well_known_text %></td>
        <td>
          <%= link_to 'Show', ticket %>
          <%= link_to 'Edit', edit_ticket_path(ticket) %>
          <%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="form-group col-sm-6">
      <span>Request Number: </span>
      <strong><%= @ticket.request_number %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Sequence Number: </span>
      <strong><%= @ticket.sequence_number %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Request Type: </span>
      <strong><%= @ticket.request_type %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Response Due DateTime: </span>
      <strong><%= @ticket.response_due_date_time %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Primary SACode: </span>
      <strong><%= @ticket.primary_service_area_code %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Additional SACode: </span>
      <strong><%= @ticket.additional_service_area_code %></strong>
    </div>
    <div class="form-group col-sm-6">
      <span>Well Known Text: </span>
      <strong><%= @ticket.well_known_text %></strong>
    </div>
</div>

<hr>

<label>Excavators:</label>
<% @ticket.excavators.each do |excavator| %>
	<%= render partial: "excavators/excavator", locals: {excavator: excavator} %>
<% end %>

<hr>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
	var polygons_text = "<%= @ticket.well_known_text %>".match(/((-){0,1}\d+(\.){0,1}\d+) ((-){0,1}\d+(\.){0,1}\d+)/g);
	var polygons_arr = [];
	polygons_text.forEach(function(pt) {
		polygons_arr.push({lng: pt.split(' ')[0] * 1 / 100000, lat: pt.split(' ')[1] * 1 / 100000});
	});

  	var handler = Gmaps.build('Google');
	handler.buildMap({ internal: {id: 'map'}}, function(){
	  var polygons = handler.addPolygons(
	    [
	      polygons_arr
	    ],
	    { strokeColor: '#FF0000'}
	  );

	  handler.bounds.extendWith(polygons);
	  handler.fitMapToBounds();
	});
</script>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>